<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Company>The Melding Wars</Company>
    <Product>NetTools</Product>
    <Authors>The Melding Wars</Authors>
    <Copyright>Copyright © 2019-2026 The Melding Wars</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <RepositoryUrl>https://github.com/themeldingwars/NetTools</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PacketDotNet" Version="0.30.3" />
    <PackageReference Include="SharpPcap" Version="4.6.1" />
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.10.94">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
